name: GH-Actions-job-Summaries

on:
  workflow_dispatch
  
jobs:
  summary:
    name: Summary
    runs-on: ubuntu-latest

    steps:
    - name: Simple job summary
      run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
    
    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: random-color-generator
    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
             
